site_name: pymata4
nav:
    - What Is Pymata4?: index.md
    - Understanding Input Data Collection: polling.md
    - The Pymata4 API:
        - The __init__ Method: init.md
        - Pin Modes: pin_modes.md
        - Enabling/Disabling Analog And Digital Reporting: enable_disable.md
        - Reading Input Data Via Polling: pin_changes.md
        - Writing To Pins And Selected Devices:  device_writes.md
        - I2C Reads And Writes: i2c.md
        - Report Requests: report_requests.md
        - Management Requests: management.md
        - Exceptions: exceptions.md
    - The Pymata4 Threading Model: concurrency.md
    - System and Installation Requirements:
        - Verifying Python 3 Version: python_3_verify.md
        - Python 3 Installation: python_install.md
        - Installing pymata4: install_pymata4.md
        - Installing FirmataExpress: firmata_express.md
    - About: about.md
    - License: license.md
theme: windmill
